; CouchDB Configuration Settings

; Custom settings should be made in this file. They will override settings
; in default.ini, but unlike changes made to default.ini, this file won't be
; overwritten on server upgrade.
[couchdb]
max_document_size = 4294967296 ; bytes
os_process_timeout = 30000
single_node = true

[cluster]
; All data is stored on the single node
n = 1
q = 1

[chttpd]
port = 5988
bind_address = 0.0.0.0
